### ISSUE TITLE
Collision viewer inaccuracy in Deku Shrine

### ISSUE THREAD

**Issue by TheTrueShadow** [HarbourMasters/2ship2harkinian#512]
- [X ] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [ X] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:

Collision viewer inaccuracy 
### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [X ] Yes, here are the steps to reproduce the bug:

### Expected behavior:

The collision viewer to properly cover the surfaces There areas can be shot and walked on but this part is just missing

### Screenshots or videos:

![image](https://github.com/HarbourMasters/2ship2harkinian/assets/80232013/19c39ec3-b60f-40b9-8773-23219fd6a617)
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/80232013/0fa742f2-98a1-48ca-88e0-f1fd29356bfa)

### System Information:
- OS: Win 11
- GFX  DirectX
- Game Version:1.0.0
- Rom Version:1.0

### Additional Information:

This happens in many spots throughout the butler race

**Comment by TheTrueShadow** [comment]
This happens in many places in Deku butler race

**Comment by Archez** [comment]
The issue displayed here is an example of two things:
* The scene collision geometry is not the same as the rendered geometry. Often they are similar, but sometimes there are inaccuracies due to precision errors from the original game developers, or intentional deviations.
* When the collision geometry is 1:1 or nearly 1:1 with the rendered geometry, there is a chance that Z-fighting can occur with other triangles

The second is what you are seeing here.

Since this is a debug tool, and we want to accurately render the collision as it is (that means showing authentic "inaccuracies"), there is nothing to fix here. I'm going to close out this issue. If you have any other questions, feel free to ask in this thread again.
