### ISSUE TITLE
Winter map Gossip Stone in Mountain Village

### ISSUE THREAD

**Issue by TheTrueShadow** [HarbourMasters/2ship2harkinian#542]
- [X] I have checked checked the known issues and searched Github to ensure this issue has not already been reported.

### Description of the inaccuracy:

The Gossip stone on the mountain village is appearing in both the winter map and the Spring map 
### Screenshots or videos of 2Ship's behavior:
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/80232013/a68195e3-8752-4c7f-b1d8-41c2b2995edb)

### Screenshots or videos of the original hardware's behavior:

Recomp
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/80232013/b590e674-992b-4d8d-b0bd-debe07c2fbf4)

KZ 
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/80232013/27e3a1e0-ae6a-4e16-8f91-2a2589010f83)

### System Information:
- OS: Windows 11
- GFX Backend:  DirectX
- Game Version: 1.0.0
- Rom Version: 1.0

### Additional Information:

The winter Gossip stone should not be there

**Comment by Archez** [comment]
Do you happen to have the `Remove Obj Dep?` toggl enabled within the Actor Viewer?
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/13861068/5817c9a0-c446-4136-9e60-dd1d77bdf665)

This toggle's behavior is to make it so that actors can spawn even when their "object file" isn't loaded.

In some scenes, the game may have actors still assigned but just the object files removed, which will prevent the actor from spawning. But if you enabled that toggle then you'll see these cases. Another such case is extra NPCs in the Milk Bar.

Unless you are intentionally playing around with spawning actors, you probably should disable this toggle for normal playthroughs.

**Comment by TheTrueShadow** [comment]
Yes I do I didn't realize it also caused that thanks
