### ISSUE TITLE
"Get a Heart Container!" Music Doesn't Play When Collecting 4th Heart Piece

### ISSUE THREAD

**Issue by lscholte** [HarbourMasters/2ship2harkinian#864]
- [x] I have checked checked the known issues and searched Github to ensure this issue has not already been reported.

### Description of the inaccuracy:
When you collect a 4th heart piece to fill a heart container, I expect to hear the "Get a Heart Container!" music rather than the "Small Item Catch" music that ordinarily plays when getting heart pieces 1-3.

### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version: 1.1.1
- Rom Version: N64 USA

### Additional Information:
I was looking through the code and saw this in `z_player.c` which appears to imply that "Get a Heart Container!" should be playing when collecting the 4th container.
```
            if ((this->getItemId == GI_HEART_CONTAINER) ||
                ((this->getItemId == GI_HEART_PIECE) && EQ_MAX_QUEST_HEART_PIECE_COUNT)) {
                seqId = NA_BGM_GET_HEART | 0x900;
            }
```

**Comment by Archez** [comment]
Yes, this is an authentic bug with the US version of mm, and the US version is what was decomped.

The problem happens because by the time this check is hit, the game has already given the player the heart piece, and so the quest count is already reset to 0.

I'm going to turn this into a feature request since its not a 2Ship bug.
We could add a "Fix" toggle to address this by changing the check to look for a quest count of 0 using our `GameInteractor_Should` hook pattern.

**Comment by lscholte** [comment]
@Archez I decided to look into fixing this myself. So I put up a PR doing what you have suggested.
