### ISSUE TITLE
Custom Keyboard Input Not Working

### ISSUE THREAD

**Issue by Smk19911** [HarbourMasters/2ship2harkinian#868]
Can't configure your own keyboard inputs "Press any button, move any axis, or press any key to edit mapping" Remains on the screen regardless of trying every key on the keyboard, it simply doesn't allow you to, you're stuck to using the default inputs only
![1](https://github.com/user-attachments/assets/10812824-e383-4c01-be7c-685be63f01c9)
![2](https://github.com/user-attachments/assets/ce50ed66-3a4a-4456-a763-686b5e172f97)

**Comment by Malkierian** [comment]
Make sure that window is fully within the bounds of the main game window, or use the Esc menu's version instead.

**Comment by Smk19911** [comment]
> Make sure that window is fully within the bounds of the main game window, or use the Esc menu's version instead.

Thanks, it seems that only Esc Works, so whomsoever have this problem too in the future: Don't use F1 to configure keyboard inputs, it doesn't work...use Esc>Settings>Input Editor!

**Comment by Malkierian** [comment]
The escape menu works because the input editor is automatically within the bounds of the main game window. The other one will still work, it just needs to not be hanging off any edges of the main game window.

That said, it's probably a good idea to get used to using the escape menu anyway, since that will be phased out in its current state in the future.
